### ISSUE TITLE
华为PLE-703L adb模式无法使用

### ISSUE THREAD

**Issue by gam2046** [8enet/AppOpsX#11]
adb执行：
`adb shell sh /sdcard/Android/data/com.zzzmode.appopsx/opsx.sh`

手机端点击任意应用后，adb输出：
```
get token f928b020671c90d1949fbe93837d2942
get classpath /storage/emulated/0/Android/data/com.zzzmode.appopsx/files/opsx/appopsx.jar
device arch arm64-v8a
get adbPort 52053
AppOpsX args: type:adb,path:52053,bgrun:1,token:f928b020671c90d1949fbe93837d2942
/sdcard/Android/data/com.zzzmode.appopsx/opsx.sh[43]: printf: not found
0


Use Ctrl+C to exit.


params --> {token=f928b020671c90d1949fbe93837d2942, bgrun=1, type=adb, path=52053}
AppOpsX server start successful, enjoy it! 馃槑
java.lang.SecurityException: uid 2000 does not have android.permission.GET_APP_OPS_STATS.
        at android.os.Parcel.readException(Parcel.java:1549)
        at android.os.Parcel.readException(Parcel.java:1502)
        at com.android.internal.app.IAppOpsService$Stub$Proxy.getOpsForPackage(IAppOpsService.java:468)
        at com.zzzmode.appopsx.server.AppOpsMain.runGet(AppOpsMain.java:210)
        at com.zzzmode.appopsx.server.AppOpsMain.handleCommand(AppOpsMain.java:189)
        at com.zzzmode.appopsx.server.AppOpsMain.onMessage(AppOpsMain.java:364)
        at com.zzzmode.appopsx.common.OpsDataTransfer.onRecvMsg(OpsDataTransfer.java:139)
        at com.zzzmode.appopsx.common.OpsDataTransfer.handleRecv(OpsDataTransfer.java:132)
        at com.zzzmode.appopsx.server.OpsXServer.run(OpsXServer.java:54)
        at com.zzzmode.appopsx.server.AppOpsMain.<init>(AppOpsMain.java:134)
        at com.zzzmode.appopsx.server.AppOpsMain.main(AppOpsMain.java:58)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
java.lang.SecurityException: uid 2000 does not have android.permission.GET_APP_OPS_STATS.
        at android.os.Parcel.readException(Parcel.java:1549)
        at android.os.Parcel.readException(Parcel.java:1502)
        at com.android.internal.app.IAppOpsService$Stub$Proxy.getOpsForPackage(IAppOpsService.java:468)
        at com.zzzmode.appopsx.server.AppOpsMain.runGet(AppOpsMain.java:210)
        at com.zzzmode.appopsx.server.AppOpsMain.handleCommand(AppOpsMain.java:189)
        at com.zzzmode.appopsx.server.AppOpsMain.onMessage(AppOpsMain.java:364)
        at com.zzzmode.appopsx.common.OpsDataTransfer.onRecvMsg(OpsDataTransfer.java:139)
        at com.zzzmode.appopsx.common.OpsDataTransfer.handleRecv(OpsDataTransfer.java:132)
        at com.zzzmode.appopsx.server.OpsXServer.run(OpsXServer.java:54)
        at com.zzzmode.appopsx.server.AppOpsMain.<init>(AppOpsMain.java:134)
        at com.zzzmode.appopsx.server.AppOpsMain.main(AppOpsMain.java:58)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
```

**Comment by 8enet** [comment]
比如用下面这条命令可以获取到正确信息吗?
`adb shell appops get com.zzzmode.appopsx`

**Comment by gam2046** [comment]
@8enet 基本断定是由于adb的权限不够导致，EMUI默认对于adb的权限较低。抱歉打扰到你。
