### ISSUE TITLE
Permission usage shows nothing in Android 9.0

### ISSUE THREAD

**Issue by ttimasdf** [8enet/AppOpsX#45]
Android 9.0 change the field name from `mTime` to `mTimes` of `android.app.AppOpsManager.OpEntry` somewhere between [Oreo](http://androidxref.com/8.1.0_r33/xref/frameworks/base/core/java/android/app/AppOpsManager.java#1246) and [Pie](http://androidxref.com/9.0.0_r3/xref/frameworks/base/core/java/android/app/AppOpsManager.java#1554). And the same as `mRejectTime` ([Source](http://androidxref.com/9.0.0_r3/xref/frameworks/base/core/java/android/app/AppOpsManager.java#1555)) Causing the package usage stats not being collected.

Error message from `opsx.sh`:
```
java.lang.NoSuchFieldException: No field mRejectTime in class Landroid/app/AppOpsManager$OpEntry; (declaration of 'android.app.AppOpsManager$OpEntry' appears in /system/framework/framework.jar)
	at java.lang.Class.getDeclaredField(Native Method)
	at com.zzzmode.appopsx.common.ReflectUtils.getFieldValue(ReflectUtils.java:70)
	at com.zzzmode.appopsx.common.ReflectUtils.getLongFieldValue(ReflectUtils.java:97)
	at com.zzzmode.appopsx.common.ReflectUtils.opsConvert(ReflectUtils.java:42)
	at com.zzzmode.appopsx.remote.AppOpsHandler.runGet(AppOpsHandler.java:99)
	at com.zzzmode.appopsx.remote.AppOpsHandler.handleCommand(AppOpsHandler.java:74)
	at com.zzzmode.appopsx.remote.AppOpsHandler.proxyInvoke(AppOpsHandler.java:58)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.zzzmode.appopsx.common.MethodUtils.invokeExactMethod(MethodUtils.java:398)
	at com.zzzmode.appopsx.server.RemoteHandler.callClass(RemoteHandler.java:310)
	at com.zzzmode.appopsx.server.RemoteHandler.onMessage(RemoteHandler.java:151)
	at com.zzzmode.appopsx.common.OpsDataTransfer.onRecvMsg(OpsDataTransfer.java:144)
	at com.zzzmode.appopsx.common.OpsDataTransfer.handleRecv(OpsDataTransfer.java:137)
	at com.zzzmode.appopsx.server.OpsXServer.run(OpsXServer.java:62)
	at com.zzzmode.appopsx.server.RemoteHandler.start(RemoteHandler.java:84)
	at com.zzzmode.appopsx.server.AppOpsMain.<init>(AppOpsMain.java:138)
	at com.zzzmode.appopsx.server.AppOpsMain.<init>(AppOpsMain.java:19)
	at com.zzzmode.appopsx.server.AppOpsMain$1.run(AppOpsMain.java:60)
	at java.lang.Thread.run(Thread.java:784)
```
On EMUI 9, Android 9.0

**Comment by ttimasdf** [comment]
`mTimes` also changed from an integer to an array recording usage timestamps at different running states.

![screenshot_20190121_181049_rikka appops](https://user-images.githubusercontent.com/2762704/51467775-4d4b4300-1da8-11e9-80aa-ed5a54171aee.jpg)
